/**
 * Sci-Fi Alien Name Generator for Octopai Arms
 * 
 * Inspired by Adrian Tchaikovsky's "Children of Time" series:
 * - "Children of Time" - Portia jumping spiders and their evolved civilization
 * - "Children of Ruin" - Octopi (Paul) and their consciousness experiments
 * 
 * Names are generated by combining prefixes with suffixes to create
 * alien-sounding names that feel both scientific and otherworldly.
 */

// Prefixes inspired by spider/cephalopod genera and sci-fi naming conventions
const PREFIXES = [
  // From jumping spider genera (Portia's relatives)
  "Port", "Bianc", "Farin", "Viol", "Sal", "Cyr", "Phal", "Marp",
  // From octopus/cephalopod genera
  "Octo", "Hapal", "Argo", "Ciru", "Vul", "Trem", "Abd", "Eus",
  // Alien/sci-fi style prefixes
  "Xen", "Zyr", "Kith", "Vor", "Thex", "Nex", "Vex", "Qor",
  "Drak", "Ix", "Ax", "Ul", "Orn", "Eth", "Ath", "Iss",
  // Neural/consciousness themed (for the uplift theme)
  "Neur", "Cog", "Syn", "Psi", "Mem", "Sen", "Cort", "Gan",
  // Space/cosmic themed
  "Astr", "Cos", "Lun", "Sol", "Neb", "Vac", "Orb", "Gal",
  // Bio/organic themed
  "Bio", "Chit", "Ceph", "Mant", "Arch", "Proto", "Endo", "Exo",
] as const;

// Suffixes that create flowing, alien-sounding endings
const SUFFIXES = [
  // Spider-inspired (Latin/scientific style)
  "ia", "ix", "us", "ax", "ora", "ara", "ida", "idae",
  // Cephalopod-inspired
  "opus", "pod", "thus", "yx", "on", "os", "as", "is",
  // Alien/ethereal
  "iel", "ael", "oth", "eth", "yn", "an", "en", "in",
  "ar", "or", "ur", "ir", "al", "el", "il", "ol",
  // Longer, more elaborate endings
  "ius", "eus", "aia", "eia", "ion", "eon", "ian", "ean",
  "rix", "rax", "nex", "lex", "tex", "dex", "vex", "pex",
  // Consciousness/neural themed
  "apse", "axon", "ode", "ome", "ine", "ene", "ase", "ate",
] as const;

// Epithets that can be optionally appended for extra flair
const EPITHETS = [
  // Descriptive traits
  "Prime", "Alpha", "Nova", "Zero", "One", "Null",
  // Colors (spiders are often color-named)
  "Crimson", "Azure", "Obsidian", "Amber", "Jade", "Onyx",
  // Scientific ranks
  "Major", "Minor", "Rex", "Apex", "Core", "Node",
  // States of being
  "Awake", "Dreaming", "Seeking", "Weaving", "Watching",
  // Elements
  "Void", "Flux", "Drift", "Spin", "Wave", "Pulse",
] as const;

// Classic names from the books (used rarely for special occasions)
const CLASSIC_NAMES = [
  // Spiders from Children of Time
  "Portia", "Bianca", "Fabian", "Viola", "Yusuf",
  // Octopi from Children of Ruin  
  "Paul", "Helena", "Meshner",
  // Other memorable characters
  "Avrana", "Holsten", "Lain", "Guyen",
] as const;

// Playful creative names inspired by Bingo & Bluey episodes
const BINGO_BLUEY_NAMES = [
  "Copernicus",
  "Gerald",
  "Featherwand",
  "Sparklegirl",
  "Fluffnut",
  "Pom Pom",
  "Professor Pancake",
  "Princess Sparklehorse",
] as const;

/**
 * Generate a random alien name for an arm
 * 
 * @param includeEpithet - Whether to sometimes include an epithet (default: 30% chance)
 * @param useClassic - Whether to rarely use a classic name from the books (default: 5% chance)
 * @returns A unique alien-sounding name
 */
export function generateArmName(includeEpithet = true, useClassic = true): string {
  // 5% chance to use a classic name from the books
  if (useClassic && Math.random() < 0.05) {
    const classic = CLASSIC_NAMES[Math.floor(Math.random() * CLASSIC_NAMES.length)];
    return classic ?? "Portia";
  }

  // 5% chance to use a Bingo/Bluey creative name
  if (Math.random() < 0.05) {
    const playful = BINGO_BLUEY_NAMES[Math.floor(Math.random() * BINGO_BLUEY_NAMES.length)];
    return playful ?? "Copernicus";
  }

  // Generate a combined name from prefix + suffix
  const prefix = PREFIXES[Math.floor(Math.random() * PREFIXES.length)] ?? "Port";
  const suffix = SUFFIXES[Math.floor(Math.random() * SUFFIXES.length)] ?? "ia";
  
  let name = prefix + suffix;
  
  // Capitalize properly (already done by construction, but ensure)
  name = name.charAt(0).toUpperCase() + name.slice(1).toLowerCase();
  
  // 30% chance to add an epithet
  if (includeEpithet && Math.random() < 0.3) {
    const epithet = EPITHETS[Math.floor(Math.random() * EPITHETS.length)] ?? "Prime";
    name = `${name}-${epithet}`;
  }
  
  return name;
}

/**
 * Generate a list of unique arm names
 * 
 * @param count - Number of names to generate
 * @returns Array of unique names
 */
export function generateArmNames(count: number): string[] {
  const names = new Set<string>();
  let attempts = 0;
  const maxAttempts = count * 10;
  
  while (names.size < count && attempts < maxAttempts) {
    names.add(generateArmName());
    attempts++;
  }
  
  return Array.from(names);
}

/**
 * Check if a name looks like it was auto-generated
 * (Useful for detecting if user provided a custom name)
 */
export function isGeneratedName(name: string): boolean {
  // Check if it matches the pattern of generated names
  const baseName = name.split("-")[0] ?? name;
  const lowerBase = baseName.toLowerCase();
  
  // Check classic names
  if (CLASSIC_NAMES.some(c => c.toLowerCase() === lowerBase)) {
    return true;
  }

  // Check playful Bingo/Bluey names
  if (BINGO_BLUEY_NAMES.some(c => c.toLowerCase() === lowerBase)) {
    return true;
  }
  
  // Check if it starts with a known prefix
  return PREFIXES.some(p => lowerBase.startsWith(p.toLowerCase()));
}

/**
 * Get statistics about the name generator
 */
export function getNameGeneratorStats(): { 
  prefixes: number; 
  suffixes: number; 
  epithets: number;
  classics: number;
  baseCombinations: number;
  withEpithets: number;
  total: number;
} {
  const baseCombinations = PREFIXES.length * SUFFIXES.length;
  const withEpithets = baseCombinations * EPITHETS.length;
  
  return {
    prefixes: PREFIXES.length,
    suffixes: SUFFIXES.length,
    epithets: EPITHETS.length,
    classics: CLASSIC_NAMES.length,
    baseCombinations,
    withEpithets,
    total: baseCombinations + withEpithets + CLASSIC_NAMES.length,
  };
}
