/**
 * PreparedTaskModal - Review and save a task definition generated by the
 * preparation agent from a discussion.
 */
import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { X, Sparkles, Plus, Check, Loader2 } from 'lucide-react';
import { api, type PreparedTaskDefinition, type Task, type TaskMetadata } from '@/lib/api';

interface PreparedTaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreated?: (task: Task) => void;
  taskId: string;
  prepared: PreparedTaskDefinition | null;
  isLoading: boolean;
  error: string | null;
}

const PRIORITY_OPTIONS: { value: PreparedTaskDefinition['priority']; label: string; color: string }[] = [
  { value: 'critical', label: 'Critical', color: 'text-red-500' },
  { value: 'high', label: 'High', color: 'text-orange-500' },
  { value: 'normal', label: 'Normal', color: 'text-blue-500' },
  { value: 'low', label: 'Low', color: 'text-gray-500' },
];

export function PreparedTaskModal({
  isOpen,
  onClose,
  onCreated,
  taskId,
  prepared,
  isLoading,
  error,
}: PreparedTaskModalProps) {
  const [subject, setSubject] = useState('');
  const [description, setDescription] = useState('');
  const [context, setContext] = useState('');
  const [requirements, setRequirements] = useState<string[]>([]);
  const [acceptanceCriteria, setAcceptanceCriteria] = useState<string[]>([]);
  const [priority, setPriority] = useState<PreparedTaskDefinition['priority']>('normal');
  const [classification, setClassification] = useState('');
  const [phase, setPhase] = useState('');
  const [estimatedEffort, setEstimatedEffort] = useState('');
  const [sourceRef, setSourceRef] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  useEffect(() => {
    if (prepared) {
      setSubject(prepared.subject);
      setDescription(prepared.description);
      setContext(prepared.context);
      setRequirements(prepared.requirements);
      setAcceptanceCriteria(prepared.acceptanceCriteria);
      setPriority(prepared.priority);
      setClassification(prepared.classification);
      setPhase(prepared.phase);
      setEstimatedEffort(prepared.estimatedEffort);
      setSourceRef(prepared.sourceRef || '');
      setSaveError(null);
    }
  }, [prepared]);

  if (!isOpen) return null;

  const handleCreateTask = async () => {
    if (!subject.trim() || !description.trim()) return;

    setIsSaving(true);
    setSaveError(null);

    try {
      const metadata: TaskMetadata = {
        preparedFromTaskId: taskId,
      };
      if (context.trim()) metadata.context = context.trim();
      if (requirements.length > 0) metadata.requirements = requirements;
      if (acceptanceCriteria.length > 0) metadata.acceptanceCriteria = acceptanceCriteria;
      if (estimatedEffort.trim()) metadata.estimatedEffort = estimatedEffort.trim();

      const result = await api.createTask({
        subject: subject.trim(),
        description: description.trim(),
        priority,
        phase: phase.trim() || undefined,
        sourceType: 'manual',
        sourceRef: sourceRef.trim() || undefined,
        metadata,
      });

      onCreated?.(result.task);
      onClose();
    } catch (err) {
      setSaveError(err instanceof Error ? err.message : 'Failed to create task');
    } finally {
      setIsSaving(false);
    }
  };

  const updateRequirement = (index: number, value: string) => {
    setRequirements(prev => prev.map((item, i) => (i === index ? value : item)));
  };

  const removeRequirement = (index: number) => {
    setRequirements(prev => prev.filter((_, i) => i !== index));
  };

  const addRequirement = () => {
    setRequirements(prev => [...prev, '']);
  };

  const updateCriterion = (index: number, value: string) => {
    setAcceptanceCriteria(prev => prev.map((item, i) => (i === index ? value : item)));
  };

  const removeCriterion = (index: number) => {
    setAcceptanceCriteria(prev => prev.filter((_, i) => i !== index));
  };

  const addCriterion = () => {
    setAcceptanceCriteria(prev => [...prev, '']);
  };

  const content = (
    <div className="flex w-full max-w-2xl flex-col overflow-hidden rounded-lg border border-zinc-700 bg-zinc-900 shadow-2xl relative mx-4 max-h-[90vh]">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-zinc-700">
        <div className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-amber-400" />
          <h2 className="text-lg font-semibold text-white">Prepared Task Definition</h2>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="p-1 text-zinc-400 hover:text-white rounded transition-colors"
          aria-label="Close prepared task dialog"
        >
          <X className="w-5 h-5" />
        </button>
      </div>

      {/* Body */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {isLoading ? (
          <div className="flex items-center justify-center py-12 text-zinc-400">
            <Loader2 className="h-6 w-6 animate-spin mr-2" />
            <span>The preparation agent is reviewing the discussion...</span>
          </div>
        ) : error ? (
          <div className="p-3 bg-red-500/10 border border-red-500/30 rounded-lg">
            <p className="text-sm text-red-400">{error}</p>
          </div>
        ) : (
          <>
            <div>
              <label className="block text-sm font-medium text-zinc-300 mb-1">
                Subject <span className="text-red-400">*</span>
              </label>
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                placeholder="Brief title for the task"
                className="w-full px-3 py-2 bg-zinc-800 border border-zinc-600 rounded-lg text-white placeholder-zinc-500 focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-zinc-300 mb-1">
                Description <span className="text-red-400">*</span>
              </label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Detailed description of what needs to be done..."
                rows={4}
                className="w-full px-3 py-2 bg-zinc-800 border border-zinc-600 rounded-lg text-white placeholder-zinc-500 resize-none focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-zinc-300 mb-1">
                Context
              </label>
              <textarea
                value={context}
                onChange={(e) => setContext(e.target.value)}
                placeholder="Relevant implementation context, constraints, and helpful pointers"
                rows={3}
                className="w-full px-3 py-2 bg-zinc-800 border border-zinc-600 rounded-lg text-white placeholder-zinc-500 resize-none focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-zinc-300 mb-1">Priority</label>
                <select
                  value={priority}
                  onChange={(e) => setPriority(e.target.value as PreparedTaskDefinition['priority'])}
                  className="w-full px-3 py-2 bg-zinc-800 border border-zinc-600 rounded-lg text-white focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500"
                >
                  {PRIORITY_OPTIONS.map(opt => (
                    <option key={opt.value} value={opt.value}>
                      {opt.label}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-zinc-300 mb-1">Phase</label>
                <input
                  type="text"
                  value={phase}
                  onChange={(e) => setPhase(e.target.value)}
                  placeholder="e.g., mvp, v1"
                  className="w-full px-3 py-2 bg-zinc-800 border border-zinc-600 rounded-lg text-white placeholder-zinc-500 focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500"
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-zinc-300 mb-1">Classification</label>
                <input
                  type="text"
                  value={classification}
                  onChange={(e) => setClassification(e.target.value)}
                  placeholder="e.g., development, architect"
                  className="w-full px-3 py-2 bg-zinc-800 border border-zinc-600 rounded-lg text-white placeholder-zinc-500 focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-zinc-300 mb-1">Estimated Effort</label>
                <input
                  type="text"
                  value={estimatedEffort}
                  onChange={(e) => setEstimatedEffort(e.target.value)}
                  placeholder="e.g., 2-3 hours"
                  className="w-full px-3 py-2 bg-zinc-800 border border-zinc-600 rounded-lg text-white placeholder-zinc-500 focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-zinc-300 mb-1">Source Reference</label>
              <input
                type="text"
                value={sourceRef}
                onChange={(e) => setSourceRef(e.target.value)}
                placeholder="e.g., plan line UID, issue number"
                className="w-full px-3 py-2 bg-zinc-800 border border-zinc-600 rounded-lg text-white placeholder-zinc-500 focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500"
              />
            </div>

            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block text-sm font-medium text-zinc-300">Requirements</label>
                <button
                  type="button"
                  onClick={addRequirement}
                  className="text-xs text-blue-400 hover:text-blue-300"
                >
                  + Add requirement
                </button>
              </div>
              <div className="space-y-2">
                {requirements.length === 0 && (
                  <p className="text-xs text-zinc-500 italic">No requirements defined</p>
                )}
                {requirements.map((req, index) => (
                  <div key={index} className="flex items-center gap-2">
                    <input
                      type="text"
                      value={req}
                      onChange={(e) => updateRequirement(index, e.target.value)}
                      placeholder={`Requirement ${index + 1}`}
                      className="flex-1 px-3 py-2 bg-zinc-800 border border-zinc-600 rounded-lg text-white placeholder-zinc-500 text-sm focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500"
                    />
                    <button
                      type="button"
                      onClick={() => removeRequirement(index)}
                      className="p-2 text-zinc-500 hover:text-red-400"
                      aria-label={`Remove requirement ${index + 1}`}
                    >
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                ))}
              </div>
            </div>

            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block text-sm font-medium text-zinc-300">Acceptance Criteria</label>
                <button
                  type="button"
                  onClick={addCriterion}
                  className="text-xs text-blue-400 hover:text-blue-300"
                >
                  + Add criterion
                </button>
              </div>
              <div className="space-y-2">
                {acceptanceCriteria.length === 0 && (
                  <p className="text-xs text-zinc-500 italic">No acceptance criteria defined</p>
                )}
                {acceptanceCriteria.map((criterion, index) => (
                  <div key={index} className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-green-500 flex-shrink-0" />
                    <input
                      type="text"
                      value={criterion}
                      onChange={(e) => updateCriterion(index, e.target.value)}
                      placeholder={`Criterion ${index + 1}`}
                      className="flex-1 px-3 py-2 bg-zinc-800 border border-zinc-600 rounded-lg text-white placeholder-zinc-500 text-sm focus:outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-500"
                    />
                    <button
                      type="button"
                      onClick={() => removeCriterion(index)}
                      className="p-2 text-zinc-500 hover:text-red-400"
                      aria-label={`Remove criterion ${index + 1}`}
                    >
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {saveError && (
              <div className="p-3 bg-red-500/10 border border-red-500/30 rounded-lg">
                <p className="text-sm text-red-400">{saveError}</p>
              </div>
            )}
          </>
        )}
      </div>

      {/* Footer */}
      <div className="flex items-center justify-between px-4 py-3 border-t border-zinc-700 bg-zinc-800/50">
        <span className="text-xs text-zinc-500">
          Generated from the current discussion
        </span>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-zinc-400 hover:text-white rounded-lg font-medium text-sm transition-colors"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleCreateTask}
            disabled={isSaving || isLoading || !subject.trim() || !description.trim()}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:bg-blue-600/50 text-white rounded-lg font-medium text-sm transition-colors disabled:cursor-not-allowed"
          >
            {isSaving ? (
              <>Saving...</>
            ) : (
              <>
                <Plus className="w-4 h-4" />
                Create Task
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );

  return createPortal(
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <button
        type="button"
        aria-label="Close prepared task dialog"
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />
      {content}
    </div>,
    document.body,
  );
}
