export { createSystemRoutes } from "./system";
export { createArmsRoutes, loadArmTemplate, listArmTemplates } from "./arms";
export { createActivityRoutes } from "./activity";
export { createMailRoutes } from "./mail";
export { createBrainRoutes } from "./brain";
export { createConfigRoutes } from "./config";
export { createOpenCodeRoutes } from "./opencode";
export { createGardenRoutes } from "./garden";
export { createProposalsRoutes } from "./proposals";
export { createTasksRoutes } from "./tasks";
export { createAgentsRoutes } from "./agents";
export { createDiscoveriesRoutes } from "./discoveries";
