export { createSystemRoutes } from "./system";
export { createArmsRoutes, loadArmTemplate, listArmTemplates } from "./arms";
export { createActivityRoutes } from "./activity";
export { createStatusReportsRoutes } from "./status-reports";
export { createMailRoutes } from "./mail";
export { createBrainRoutes } from "./brain";
export { createConfigRoutes } from "./config";
export { createOpenCodeRoutes } from "./opencode";
export { createGardenRoutes } from "./garden";
export { createProposalsRoutes } from "./proposals";
export { createTasksRoutes } from "./tasks";
export { createTaskDiscussionsRoutes } from "./task-discussions";
export { createTaskSummariesRoutes } from "./task-summaries";
export { createTaskDiffsRoutes } from "./task-diffs";
export { createAgentsRoutes } from "./agents";
export { createDiscoveriesRoutes } from "./discoveries";
export { createBugsRoutes } from "./bugs";
export { createEscalationRoutes } from "./escalations";
export { createEventsRoutes } from "./events";
export { createSearchRoutes } from "./search";
export { createStatusHistoryRoutes } from "./status-history";
export { createStatusSeriesRoutes } from "./status-series";
export { createUploadApiRoutes, createUploadContentRoutes } from "./uploads";
export { createOnboardingRoutes } from "./onboarding";
export { createProjectSetupRoutes } from "./project-setup";
